import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import ThemedComponent from "@/themes/themes";
import { helvetica } from "@/utils/customFonts";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Vampay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemedComponent mode={"light"}>
        <body className={`${helvetica.variable} ${poppins.className}`}>
          <Navbar />
          {children}
        </body>
      </ThemedComponent>
    </html>
  );
}

// import type { Metadata } from "next";
// import "./globals.css";
// import Navbar from "@/components/navbar/page";
// import ThemedComponent from "@/themes/themes";
// import localFont from 'next/font/local';
// import { Poppins } from 'next/font/google';

// // const helvetica = localFont({
// //   src: 'fonts/helvetica_neue/HelveticaNeueBlack.otf',
// //   display: 'swap',
// // })

// const poppins = Poppins({
//   weight: '400', // Add this line
//   subsets: ['latin'],
//   variable: '--font-inter',
//   display: 'swap',
//  })

// export const metadata: Metadata = {
//   title: "Vampay",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
//  }: {
//   children: React.ReactNode;
//  }) {
//   return (
// <html lang="en">
//   <ThemedComponent mode={'light'}>
//     <body className={poppins.className}>
//       <Navbar />
//       {children}
//     </body>
//   </ThemedComponent>
// </html>
//   );
//  }
