import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import ThemedComponent from "@/themes/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Vampay",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemedComponent mode={'light'}>
        <body className="">
          {/* className={inter.className} */}
          {/* <Navbar /> */}
          {children}
        </body>
      </ThemedComponent>
    </html>
  );
}
